=== aica-technology/component-sdk/schema/schema/component.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "id": "https://github.com/aica-technology/dynamic-components/schema/schema/component.schema.json",
  "title": "Dynamic Component Description",
  "description": "A full description of a dynamic component in the AICA application framework.",
  "type": "object",
  "properties": {
    "name": {
      "description": "The human-readable name of the component.",
      "type": "string"
    },
    "description": {
      "description": "The human-readable description of this component and its behaviour.",
      "type": "object",
      "properties": {
        "brief": {
          "description": "A brief (one-line) description of the component for quick reference and tool-tips.",
          "type": "string"
        },
        "details": {
          "description": "An optional detailed description of the component.",
          "type": "string"
        }
      },
      "required": [
        "brief"
      ]
    },
    "registration": {
      "$ref": "#/$defs/registration"
    },
    "is_lifecycle": {
      "description": "Specify if the component is a managed node with lifecycle states.",
      "type": "boolean"
    },
    "inherits": {
      "oneOf": [
        {
          "$ref": "#"
        },
        {
          "$ref": "#/$defs/registration"
        }
      ]
    },
    "inputs": {
      "description": "The fixed input signals (subscriptions) of the component.",
      "type": "array",
      "items": {
        "$ref": "signal.schema.json"
      },
      "uniqueItems": true
    },
    "input_collections": {
      "description": "The dynamically assignable input signals (subscriptions) of the component.",
      "type": "array",
      "items": {
        "$ref": "signal_collection.schema.json"
      },
      "uniqueItems": true
    },
    "outputs": {
      "description": "The output signals (publications) of the component.",
      "type": "array",
      "items": {
        "$ref": "signal.schema.json"
      },
      "uniqueItems": true
    },
    "parameters": {
      "description": "The parameters declared by the component.",
      "type": "array",
      "items": {
        "$ref": "parameter.schema.json"
      },
      "uniqueItems": true
    },
    "predicates": {
      "description": "The predicates provided by the component.",
      "type": "array",
      "items": {
        "$ref": "predicate.schema.json"
      },
      "uniqueItems": true
    },
    "services": {
      "description": "The services provided by the component.",
      "type": "array",
      "items": {
        "$ref": "service.schema.json"
      },
      "uniqueItems": true
    }
  },
  "required": [
    "name",
    "description",
    "registration",
    "is_lifecycle"
  ],
  "$defs": {
    "registration": {
      "description": "The registration details of the exported component required for run-time loading.",
      "type": "object",
      "properties": {
        "package": {
          "description": "The name of the package in which this component is defined.",
          "type": "string"
        },
        "class": {
          "description": "The fully qualified class name used to register the component.",
          "type": "string"
        }
      },
      "required": [
        "package",
        "class"
      ]
    }
  }
}

=== aica-technology/component-sdk/schema/examples/foo.json
{
  "name": "Foo",
  "description": {
    "brief": "An example component",
    "details": "A longer description of the example component"
  },
  "registration": {
    "package": "foo_package",
    "class": "foo_package::Foo"
  },
  "is_lifecycle": false,
  "inputs": [
    {
      "display_name": "Input 1",
      "description": "An example input",
      "signal_type": "bool",
      "signal_topic": "~/foo_in"
    }
  ],
  "input_collections": [
    {
      "display_name": "Input Collection 1",
      "description": "An example dynamic input collection",
      "signal_type": "int",
      "topic_array_parameter": "foo_dynamic_in_1_topic_names"
    },
    {
      "display_name": "Input Collection 2",
      "description": "Another example dynamic input collection with default initial inputs",
      "signal_type": "string",
      "topic_array_parameter": "foo_dynamic_in_2_topic_names",
      "signal_topic_array": [
        "~/default_in_x",
        "~/default_in_y",
        "~/default_in_z"
      ]
    },
    {
      "display_name": "Input Collection 3",
      "description": "Another example dynamic input collection with configurable type",
      "signal_type": "joint_positions",
      "topic_array_parameter": "foo_dynamic_in_3_topic_names",
      "configurable_type": true,
      "type_parameter": "foo_dynamic_in_3_type",
      "supported_types": ["joint_positions", "joint_state"]
    }
  ],
  "outputs": [
    {
      "display_name": "Output 1",
      "description": "An example output",
      "signal_type": "cartesian_pose",
      "signal_topic": "~/foo_out_1",
      "configurable_topic": true,
      "topic_parameter": "foo_out_1_topic_name"
    },
    {
      "display_name": "Output 2",
      "description": "Another example output",
      "signal_type": "cartesian_state",
      "signal_topic": "~/foo_out_2",
      "configurable_type": true,
      "type_parameter": "foo_out_2_type",
      "supported_types": ["cartesian_pose", "cartesian_twist", "cartesian_state"]
    }
  ],
  "parameters": [
    {
      "display_name": "Parameter X",
      "description": "An example parameter",
      "parameter_name": "parameter_x",
      "parameter_type": "int"
    },
    {
      "display_name": "Parameter Y",
      "description": "An example optional parameter",
      "parameter_name": "parameter_y",
      "parameter_type": "string",
      "default_value": "some_default_value",
      "optional": true
    },
    {
      "display_name": "Parameter Z",
      "description": "An example parameter that can be dynamically reconfigured while the component is active",
      "parameter_name": "parameter_z",
      "parameter_type": "double_array",
      "dynamic": true
    }
  ],
  "predicates": [
    {
      "display_name": "Predicate Alpha",
      "description": "An example predicate",
      "predicate_name": "is_alpha"
    }
  ],
  "services": [
    {
      "display_name": "Trigger Service",
      "description": "An example service",
      "service_name": "trigger_something"
    },
    {
      "display_name": "Payload Service",
      "description": "An example service with a payload",
      "service_name": "trigger_something_with_parameters",
      "has_payload": true
    }
  ]
}
